sudo: required
services:
  - docker

before_install:
  - docker build -t abdulgaffersiam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abdulgaffersiam/react-test npm test

after_success:
  - docker build -t abdulgaffersiam/multy-client ./client
  - docker build -t abdulgaffersiam/multy-nginx ./nginx
  - docker build -t abdulgaffersiam/multy-server ./server
  - docker build -t abdulgaffersiam/multy-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push into docker hub
  - docker push abdulgaffersiam/multy-client
  - docker push abdulgaffersiam/multy-nginx
  - docker push abdulgaffersiam/multy-server
  - docker push abdulgaffersiam/multy-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-648392584745'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY